### ISSUE TITLE
Doesn't remember previous message

### ISSUE THREAD

**Issue by mustafatofur** [treyworks/treyworks-chat-plugin#2]
Hi,
It doesn't remember what user says in the previous message.
It answer for t he first time and never remember the previous message.

I also want to emphasize that would add function calling or reading file through assistant.

**Comment by treyworks** [comment]
Hello,

We've resolved the problem where past messages were not being retained in the most recent commit and release. Thank  you for evaluating the plugin and sharing your insights.

We're looking into introducing features for function invocation and managing assistants in upcoming releases. For now, you'll need to manually include any reference files to your assistants through the OpenAI Assistant administration interface.
